plugins { id 'com.android.application' }

android {
    namespace 'lt.tyliaitpk.etn'
    compileSdk 36
    defaultConfig {
        applicationId 'lt.tyliaitpk.etn.next'
        minSdk 26
        targetSdk 36
        versionCode 36
        versionName '0.6.18'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

